# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install arm compilers
      run: sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
    - name: Build all
      run: make all
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "esc-arm,esc-arm64,esc-amd64"
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitPrereleaseDuringUpdate: true

